apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgset-sa
  namespace: "{{ .Release.Namespace }}"

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgset-role
  namespace: "{{ .Release.Namespace }}"
rules:
- apiGroups:
  - '*'
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pgset-binding
  namespace: "{{ .Release.Namespace }}"
subjects:
- kind: ServiceAccount
  name: pgset-sa
  namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: Role
  name: pgset-role
  apiGroup: rbac.authorization.k8s.io
